### ISSUE TITLE
Mimic the API in node-libcurl

### ISSUE THREAD

**Issue by azawawi** [azawawi/perl6-net-curl#15]
https://www.npmjs.com/package/node-libcurl

**Comment by CurtTilmes** [comment]
I started working on a more Perl-ish OO approach to libcurl as a patch to Net::Curl, but I kind of got carried away and replaced the whole thing -- https://github.com/CurtTilmes/perl6-libcurl  I don't intend any disrepect, I appreciate the effort you put into Net::Curl, but I hope you'll take a look.

**Comment by azawawi** [comment]
No worries. Game on 👍 

Competition is healthy :)

**Comment by azawawi** [comment]
@CurtTilmes Nice job on the documentation/API end 👍

**Comment by CurtTilmes** [comment]
Thanks!
