### ISSUE TITLE
Support? and example usage of CURLOPT_HTTPHEADER

### ISSUE THREAD

**Issue by 7ojo** [azawawi/perl6-net-curl#20]
I'm trying to pass authentication headers through CURLOPT_HTTPHEADER with no luck using NativeCall API. Would be nice to get example about it :)

See https://curl.haxx.se/libcurl/c/CURLOPT_HTTPHEADER.html

**Comment by azawawi** [comment]
Unfortunately this is not supported by this library. Please take a look at [libcurl](https://github.com/CurtTilmes/perl6-libcurl). It has a type for `LibCurl::slist` in its `LibCurl::Easy` class.

Thanks 👍
